### ISSUE TITLE
Web based mobile client

### ISSUE THREAD

**Issue by joeblew99** [viru/berrybot#8]
Hey, this is really an awesome project.

I am wanting to extend it a bit to test out some self driving ideas, but I need a much better mobile GUI.

So I am trying to work out how to expose the grpc golang up to a Cordova based web application.
Maybe you have some ideas of how to do this ?

These days with grpc it's possible to use web sockets between the Cordova GUI and the grpc golang code with bidirectional sockets. But I can't work out how to connect the Cordova layer up to the GRPC layer.

Thanks in advance

**Comment by pawelkowalak** [comment]
I'm glad you like it :) I don't have experience with Cordova and I couldn't find websockets solution you mention. I'm only aware of gRPC-JSON gateway: https://github.com/grpc-ecosystem/grpc-gateway

But it doesn't support bidirectional streams which I'm using in this project. So probably native app for iOS/Android is the way to go if you want fancy UI :)
